# aliases
if [[ -f ~/.dotfiles/zsh/aliases ]]; then
    source ~/.dotfiles/zsh/aliases
fi

# job stuff
if [[ -f ~/.dotfiles/zsh/zshrc_extra ]]; then
	source ~/.dotfiles/zsh/zshrc_extra
fi

# custom functions
fpath=(
  ~/.dotfiles/zsh/functions 
  ~/.dotfiles/zsh/functions/extra
  ~/.dotfiles/zsh/completion
  "${fpath[@]}"
)
autoload -Uz $fpath[1]/*(.:t)
autoload -Uz $fpath[2]/*(.:t)
autoload -Uz $fpath[3]/*(.:t)

# completions
source <(kubectl completion zsh)
autoload -Uz compinit && compinit -i

# mcfly
eval "$(mcfly init zsh)"

# pyenv
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# the fuck
eval $(thefuck --alias)

# plugins
for file in ~/.dotfiles/zsh/plugins/*; do
  source "$file"
done
