# aliases
if [[ -f ~/.dotfiles/zsh/aliases ]]; then
    source ~/.dotfiles/zsh/aliases
fi

# theme
source ~/.dotfiles/zsh/themes/kevin.zsh-theme

# completions
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit -i
source <(kubectl completion zsh)

# mcfly
eval "$(mcfly init zsh)"

# pyenv
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# the fuck
eval $(thefuck --alias)

# plugins
for file in ~/.dotfiles/zsh/plugins/*; do
  source "$file"
done

# custom functions
fpath=(
  ~/.dotfiles/zsh/functions 
  ~/.dotfiles/zsh/functions/omz
  ~/.dotfiles/zsh/functions/extra
  ~/.dotfiles/zsh/completion
  $fpath
)
autoload -Uz $fpath[1]/*(.:t)
autoload -Uz $fpath[2]/*(.:t)
autoload -Uz $fpath[3]/*(.:t)
autoload -Uz $fpath[4]/*(.:t)

# extras that are in .gitignore
if [[ -f ~/.dotfiles/zsh/zshrc_extra ]]; then
	source ~/.dotfiles/zsh/zshrc_extra
fi

