# aliases
alias c="clear"
alias cdc="cd ~/Code"
alias cdo="cd -"
alias d="docker"
alias dc="docker-compose"
alias f="fuck"
alias grep="grep --color"
alias ipy="ipython"
alias k="kubectl"
alias ls="ls --color -F"
alias la="ls -a"
alias prev="open -a preview"
alias sz="source ~/.zshrc"
alias tf="terraform"

## git
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gd="git diff"
alias gch="git checkout"
alias gcl="git clone --recurse-submodules"
alias gl="git pull"
alias gp="git push"
alias gs="git status"
alias gsw="git switch"

## localstack
alias awsl="aws --endpoint-url=http://localhost:4566"

## random
alias rmsc="rm -f ~/Desktop/Screenshots/*"

# set editor
export EDITOR=nvim
bindkey -e

# pyenv
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# custom functions
fpath=(
  ~/.dotfiles/zsh/functions 
  ~/.dotfiles/zsh/completion
  $fpath
)
autoload -Uz $fpath[1]/*(.:t)
autoload -Uz $fpath[2]/*(.:t)

# completions
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit -i
source <(kubectl completion zsh)

# extras that are in .gitignore
if [[ -f ~/.dotfiles/zsh/zshrc_extra ]]; then
	source ~/.dotfiles/zsh/zshrc_extra
fi

# ls colors
# macOS only
export CLICOLOR=1

# GNU 
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# starship prompt
eval "$(starship init zsh)"

# cargo
export PATH=$PATH:~/.cargo/bin
